/**
 * PDF report generation for PermitCheck.
 * Generates HTML-based PDF reports using a server-side rendering approach.
 * In production, consider Puppeteer for pixel-perfect output.
 *
 * For MVP, we generate a structured HTML report that can be printed to PDF
 * from the client, and store the report data for server-side generation.
 */

import { DISCLAIMER } from "./config";
import type { Permit } from "@/types";

export interface ReportData {
  address: string;
  lookupDate: string;
  lookupId: string;
  permits: Permit[];
  reportType: "standard" | "attorney";
  matterReference?: string;
}

/**
 * Generate HTML content for the PDF report.
 * This HTML can be converted to PDF via Puppeteer or served directly.
 */
export function generateReportHtml(data: ReportData): string {
  const { address, lookupDate, lookupId, permits, reportType } = data;

  const statusColor: Record<string, string> = {
    Issued: "#22c55e",
    Expired: "#ef4444",
    "In Review": "#f59e0b",
    Finaled: "#3b82f6",
    Void: "#6b7280",
    Pending: "#f59e0b",
    Unknown: "#9ca3af",
  };

  const permitRows = permits
    .sort(
      (a, b) =>
        new Date(b.filed_date || 0).getTime() -
        new Date(a.filed_date || 0).getTime()
    )
    .map(
      (p) => `
    <tr>
      <td>${p.record_number}</td>
      <td>${p.type}</td>
      <td><span style="color: ${statusColor[p.status] || "#9ca3af"}; font-weight: 600;">${p.status}</span></td>
      <td>${p.filed_date || "N/A"}</td>
      <td>${p.issued_date || "N/A"}</td>
      <td>${p.description || "—"}</td>
      <td>${p.contractor || "—"}</td>
    </tr>
  `
    )
    .join("");

  const attorneyCoverPage =
    reportType === "attorney"
      ? `
    <div style="page-break-after: always; padding: 60px; text-align: center;">
      <h1 style="font-size: 28px; margin-bottom: 40px;">PERMIT HISTORY REPORT</h1>
      <h2 style="font-size: 20px; color: #666; margin-bottom: 60px;">Prepared for Legal Use</h2>
      <table style="margin: 0 auto; text-align: left; font-size: 14px;">
        <tr><td style="padding: 8px 20px; font-weight: bold;">Property Address:</td><td style="padding: 8px 20px;">${address}</td></tr>
        <tr><td style="padding: 8px 20px; font-weight: bold;">Report Date:</td><td style="padding: 8px 20px;">${lookupDate}</td></tr>
        <tr><td style="padding: 8px 20px; font-weight: bold;">Report ID:</td><td style="padding: 8px 20px;">${lookupId}</td></tr>
        <tr><td style="padding: 8px 20px; font-weight: bold;">Data Source:</td><td style="padding: 8px 20px;">City of Atlanta Accela Public Records Database</td></tr>
        <tr><td style="padding: 8px 20px; font-weight: bold;">Records Found:</td><td style="padding: 8px 20px;">${permits.length}</td></tr>
        ${data.matterReference ? `<tr><td style="padding: 8px 20px; font-weight: bold;">Matter Reference:</td><td style="padding: 8px 20px;">${data.matterReference}</td></tr>` : ""}
      </table>
      <div style="margin-top: 80px; padding: 20px; border-top: 2px solid #333;">
        <h3>Chain of Custody</h3>
        <p style="font-size: 12px; color: #666;">
          This report was generated by PermitCheck (permitcheck.com) on ${lookupDate}.<br/>
          Data was retrieved directly from the City of Atlanta's Accela Citizen Access database.<br/>
          Report ID: ${lookupId}<br/>
          No modifications were made to the source data.
        </p>
      </div>
    </div>
  `
      : "";

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>PermitCheck Report — ${address}</title>
  <style>
    body {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      color: #1a1a1a;
      line-height: 1.5;
      margin: 0;
      padding: 40px;
      font-size: 12px;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 3px solid #1e40af;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    .logo { font-size: 24px; font-weight: 700; color: #1e40af; }
    .meta { text-align: right; color: #666; font-size: 11px; }
    h2 { color: #1e40af; font-size: 16px; margin: 24px 0 12px; }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
    }
    th {
      background: #1e40af;
      color: white;
      padding: 8px 10px;
      text-align: left;
      font-size: 11px;
      text-transform: uppercase;
    }
    td {
      padding: 8px 10px;
      border-bottom: 1px solid #e5e7eb;
      font-size: 11px;
    }
    tr:nth-child(even) { background: #f9fafb; }
    .disclaimer {
      margin-top: 40px;
      padding: 16px;
      background: #fef3c7;
      border: 1px solid #f59e0b;
      font-size: 10px;
      color: #92400e;
      line-height: 1.6;
    }
    .footer {
      margin-top: 24px;
      text-align: center;
      color: #9ca3af;
      font-size: 10px;
      border-top: 1px solid #e5e7eb;
      padding-top: 12px;
    }
    .summary-box {
      background: #eff6ff;
      border: 1px solid #bfdbfe;
      padding: 16px;
      border-radius: 8px;
      margin: 16px 0;
    }
    @media print {
      body { padding: 20px; }
      .disclaimer { break-inside: avoid; }
    }
  </style>
</head>
<body>
  ${attorneyCoverPage}

  <div class="header">
    <div class="logo">PermitCheck</div>
    <div class="meta">
      Report Generated: ${lookupDate}<br/>
      Report ID: ${lookupId}
    </div>
  </div>

  <div class="summary-box">
    <strong>Property Address:</strong> ${address}<br/>
    <strong>Total Permit Records Found:</strong> ${permits.length}<br/>
    <strong>Data Source:</strong> City of Atlanta — Accela Public Records Database
  </div>

  <h2>Permit History</h2>

  ${
    permits.length > 0
      ? `
    <table>
      <thead>
        <tr>
          <th>Record #</th>
          <th>Type</th>
          <th>Status</th>
          <th>Filed Date</th>
          <th>Issued Date</th>
          <th>Description</th>
          <th>Contractor</th>
        </tr>
      </thead>
      <tbody>
        ${permitRows}
      </tbody>
    </table>
  `
      : `
    <div style="text-align: center; padding: 40px; color: #666;">
      <p style="font-size: 16px;">No permit records found for this address.</p>
      <p style="font-size: 12px;">
        This may indicate that no permits have been filed, or that records exist
        under a different address format. Consider verifying the address with the
        City of Atlanta's Department of City Planning.
      </p>
    </div>
  `
  }

  <div class="disclaimer">
    ${DISCLAIMER}
  </div>

  <div class="footer">
    PermitCheck — Atlanta Property Permit Verification<br/>
    &copy; ${new Date().getFullYear()} PermitCheck. All rights reserved.
  </div>
</body>
</html>
  `;
}
